trigger:
  - master


pool:
  vmImage: 'ubuntu-latest'

jobs:
  -job: A
    steps:
      - script: 
        npm run pre-test
      displayName: running ganache
  
  -job : B
    dependsOn: A
    steps:
      - task: Npm@1
        inputs:
          command: 'install'
        displayName: npm install

      - script: |
          npx truffle compile 
        displayName: truffle compile 

      - script:
          npx truffle test
        displayName : truffle test
