trigger:
  - master


pool:
  vmImage: 'ubuntu-latest'

stages:
  -stage: A
    steps:
      - script: 
        npm run pre-test
      displayName: running ganache
  
  -stage : B
    steps:
      - task: Npm@1
        inputs:
          command: 'install'
        displayName: npm install

      - script: |
          npx truffle compile 
        displayName: truffle compile 

      - script:
          npx truffle test
        displayName : truffle test
