trigger:
  - master

variables:
  contractName: 'WrappedXRP'

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Npm@1
    inputs:
      command: 'install'
    displayName: npm install

  - script: |
      npx truffle compile 
    displayName: truffle compile 

  - script:
      npx run test
    displayName : truffle test
