trigger:
  - master


pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Npm@1
    inputs:
      command: 'install'
    displayName: npm install

  - script: |
      npx truffle compile 
    displayName: truffle compile 
 

  - script: |
      ganache-cli --host 127.0.0.1 --port 8545 --networkId 5777 > /dev/null &
      npx truffle test --network development 
    displayName: truffle test